
models:
  - model: Qwen/Qwen2.5-7B-Instruct
  - model: Qwen/Qwen2.5-Math-7B-Instruct
    parameters:
      density: 0.9
      weight: 0.1
merge_method: breadcrumbs
base_model: Qwen/Qwen2.5-7B-Instruct
parameters:
  normalize: true
dtype: bfloat16
