base_model: Qwen/Qwen2.5-7B-Instruct

experts:
  - source_model: Qwen/Qwen2.5-7B-Instruct
  - source_model: Qwen/Qwen2.5-Math-7B-Instruct

model_kwargs:
  - device_map: cuda
  - low_cpu_mem_usage: True
  - trust_remote_code: True

weights: [0.9, 0.1]
